### ISSUE TITLE
IMAGECOLOR and GD/PNG transparency not working as expected

### ISSUE THREAD

**Issue by kempisty** [mapserver/mapserver#4346]
I am drawing a floating point raster with Mapserver 6.0.3, using GD/PNG.  In the Mapfile, I wish to classify it, and make certain valid portions of my raster transparent.  That is, NODATA should be transparent;  some parts of the raster that have perfectly valid values should also be transparent because I don't care to see them.  To accomplish this, I set the following terms in my mapfile:

    MAP
    IMAGECOLOR     254 254 254
    OUTPUTFORMAT
        NAME "png"
        DRIVER        GD/PNG
        IMAGEMODE     PC256
        TRANSPARENT   ON
    END
    
    ##
    ##... skipping irrelevant cruft ...
    ##
    
    CLASS
        # 0 thousands:  No Wx
        EXPRESSION ([pixel] < 1000 )
        STYLE
            COLOR 254 254 254
        END
    END

According to the documentation, OUTPUTFORMAT / TRANSPARENT ON should turn the background color, defined in IMAGECOLOR, into the transparency value. Then when I define a CLASS that draws the IMAGECOLOR, that CLASS should be rendered transparent as well.  That isn't happening.  That CLASS comes back opaque white(ish).

The problem appears to be in mapgd.c:78
<pre>
  if(!format->transparent && bg && MS_VALID_COLOR(*bg))
          gdImageColorAllocate(ip, bg->red, bg->green, bg->blue); /* set the background color */
  else {
          gdImageColorAllocate(ip,117,17,91); /*random bg color (same one as picked in msResampleGDALToMap) */
          gdImageColorTransparent(ip, 0);
  }
</pre>

When transparency is turned on, the transparent background color is being set to 117,17,91 instead of IMAGECOLOR  (bg->red, bg->green, bg->blue).

Workaround 1: Set IMAGECOLOR to 117 17 91 ...  and set CLASS to draw 117 17 91.  That is a kludgey thing to do, and an awfully random number to remember going forward.

Workaround 2:  I suppose I could also rewrite my classes to not draw my ignored values at all. I would prefer not to do that, since it would add to the complexity of the comparison operations.

As the code block notes, this random 117 17 91 value is also being used in msResampleGDALToMap, so transparency is likely buggy in more than one place.

**Comment by fxgamoy** [comment]
I ve got the same issue with mapserver 6.2 and mapserver 6.4.1.
php_mapscript don't care about the imagecolor parameter of the map.
My initial mapfile...
![testmap](https://cloud.githubusercontent.com/assets/2443455/8736819/2d6621e4-2c1c-11e5-88df-ce29905ca10e.png)

$this->oMap = ms_newMapObj($szMapFile);
$this->oMap->save(TMP_DIR."/log/readmapfile.map");
I obtain

![aftersavingmapfile](https://cloud.githubusercontent.com/assets/2443455/8736976/c6c90f12-2c1d-11e5-9e2e-788595406af1.png)

This works fine with mapserver 5.6. Imagcolor is well written in the saved mapfile.
It don't work anymore with mapserver 6.2+. Imagecolor is not written in the output mapfile so that 
 mapserver don't turn anymore the background color, defined in IMAGECOLOR, into the transparency value.

**Comment by jratike80** [comment]
GD rendered is removed from MS 7.0.
