### ISSUE TITLE
What is the maximum WCS export size

### ISSUE THREAD

**Issue by msmitherdc** [mapserver/mapserver#4421]
for a 64 bit instance

I'm getting messages like

```
agg2CreateImage(): Memory allocation error. mapagg.cpp: 796: Out of memory allocating 4164540520 bytes.
```

when making large (5 sq mile) wcs requests (1.0.0) against a tile index with resolution of (0.1 m).

**Comment by jratike80** [comment]
Questions belong IMHO better to mapserver-users mailing list. Three years later I asked the same question because I do not follow Github issues so closely.
http://osgeo-org.1560.x6.nabble.com/What-resourse-blocks-any-bigger-GeoTIFF-output-from-WCS-td5218584.html

I suppose that this ticket does not deal with any exact bug so I am closing it.
