### ISSUE TITLE
Use application/vnd.geo+json as MIME type for geojson

### ISSUE THREAD

**Issue by jratike80** [mapserver/mapserver#4929]
MIME type has been registered on 2014-05-20
http://www.iana.org/assignments/media-types/application/vnd.geo+json

**Comment by jrahkonen** [comment]
Adding some information to this issue even it is closed by the bot.

After the latest update to GeoJSON https://tools.ietf.org/html/draft-ietf-geojson-04 mime type "application/geo+json" must not be used if the geospatial json file contains crs.
Reference: mail by Sean Gilles http://lists.geojson.org/pipermail/geojson-geojson.org/2016-June/000999.html. So that alone justifies closing this ticket as Won't fix.

>"Web services that return legacy 2008 GeoJSON should never use
"Content-type: application/geo+json" in response headers. This is plainly
wrong. The proper content type to use for legacy 2008 GeoJSON was never
standardized. Many providers used "application/json", which remains a good
option and is distinct from "application/geo+json"".

http://lists.geojson.org/pipermail/geojson-geojson.org/2016-June/000999.html
