### ISSUE TITLE
FeatureCollection BBOX missing from GeoJSON

### ISSUE THREAD

**Issue by nthsense** [mapserver/mapserver#4947]
I have a layer that I can return as either GML or GeoJSON when I post a GetFeature request.  When the GML returns, it has a boundedBy element which contains the extents of the features.  However, when I request it as GeoJSON, I don't get a bbox at the FeatureCollection level as I should.

In my GeoJSON OUTPUTFORMAT definition, I am using FORMATOPTION "LCO:WRITE_BBOX=YES".  This should give me bboxes for each Feature, as well as for the FeatureCollection (see http://www.gdal.org/drv_geojson.html).  

If I use my GML as a test in ogr2ogr, it does put the bbox element into the GeoJSON in all the right places.  I use this command:

ogr2ogr -f "GeoJSON" results.json test.gml -lco WRITE_BBOX=YES

The fact that this works tells me the issue is likely not at the OGR level, but at the Mapserver level.

**Comment by jratike80** [comment]
Works for with Mapserver 7.0 with GDAL 2.0.0 from MS4W 3.1.0. Having FORMATOPTION "LCO:WRITE_BBOX=YES" in the mapfile adds bbox into each feature and info FeatureCollection. However, the bbox of FeatureCollection comes at the very end, after the last feature and ends the GeoJSON file. I suppose it is OK because both jsonlint.com and geojsonlint.com accept the output. Here is how the GeoJSON resultset ends:

],
"bbox": [ -124.731422, 24.955967, -66.969849, 49.371735 ]
}

@rouault , please close if it is really OK to put the bbox of the FeatureCollection after the features.

**Comment by rouault** [comment]
Yes the order doesn't matter. And technically it wouldn't be possible to write it before the features since we don't know it at that point
