### ISSUE TITLE
In Cluster: wrong name Cluster_FeatureCount

### ISSUE THREAD

**Issue by aperi2007** [mapserver/mapserver#5021]
Hi,

I notice in mapclust.c the
name
LabelItem "Cluster:FeatureCount" 
is not recognized

It is knowed as

LabelItem "Cluster_FeatureCount"

I see the code:

#define MSCLUSTER_FEATURECOUNT "Cluster_FeatureCount"

I guess it is wrong accordly to the documentation.

A.

**Comment by jratike80** [comment]
In MS 7.0 documentation http://mapserver.org/mapfile/cluster.html "Cluster_FeatureCount" is used in all places.

Old documentation for 6.4 seems to be hidden somewhere, at least I can't find it here:
http://mapserver.org/download.html
Because it is hard or impossible to find wrong documentation I am closing this issue.
