### ISSUE TITLE
WFS GetFeature with full extents BBOX fails

### ISSUE THREAD

**Issue by mfarwell** [mapserver/mapserver#5024]
Mapserver 6.x

Posting the following WFS 1.1.0 GetFeature request fails:

`<ogc:Filter>`
  `<ogc:BBOX>`
    `<ogc:PropertyName/>`
    `<gml:Envelope srsDimension="2" srsName="urn:x-ogc:def:crs:EPSG:4326">`
      `<gml:lowerCorner>-180 -90</gml:lowerCorner>`
      `<gml:upperCorner>180 90</gml:upperCorner>`
    `</gml:Envelope>`
  `</ogc:BBOX>`
`</ogc:Filter>`

However, breaking the BBOX up into 4 quadrants returns the expected results.  It seems related to geographic coverages greater than 180 degrees.

**Comment by jratike80** [comment]
srsName="urn:x-ogc:def:crs:EPSG:4326" should use latitude-longitude axis order with WFS 1.1.0. If using quadrants return expected result, then it is unexpected.

**Comment by jratike80** [comment]
With Mapserver 7.0 this BBOX filter works for me. Notice lat-lon order.

<ogc:Filter> 
<ogc:BBOX> <ogc:PropertyName/>
 <gml:Envelope srsDimension="2" srsName="urn:x-ogc:def:crs:EPSG:4326">
 <gml:lowerCorner>-90 -180</gml:lowerCorner> 
<gml:upperCorner>90 180 </gml:upperCorner>
 </gml:Envelope>
 </ogc:BBOX>
 </ogc:Filter> 

Thus "WFS GetFeature with full extents BBOX fails" is not generally true because it works for me. It may still fail with some other configuration. Reopen and add more details if that still happens for you.
