### ISSUE TITLE
msLoadMap breaks on Unknown identifier.

### ISSUE THREAD

**Issue by NathanW2** [mapserver/mapserver#5093]
Using mapscript to read a map file with an unknown identifier it will crash with:

```
this = _mapscript.new_mapObj(filename)
_mapscript.MapServerError: msLoadMap(): Unknown identifier. Parsing error near (PIXELADJUSTMENT):(line 8)
```

Might be a better idea to ignore unknown identifiers and report them in a method `parseerrors()`.

**Comment by sdlime** [comment]
I don't think this is possible because an initial error often triggers subsequent parsing errors so you simply can't skip it. For example, let's say someone misspells "LABEL" as "LABLE" which will generate unknown identifier error, and then a whole slew of subsequent errors with identifiers that are valid within the context of a label but not otherwise (e.g. FONT). Even with errors simply due to version differences it's difficult because you have subsequent tokens (e.g. values) to deal with.

Steve
