### ISSUE TITLE
Place of CONFIG section

### ISSUE THREAD

**Issue by drnextgis** [mapserver/mapserver#5131]
This config doesn't work

```
MAP
    PROJECTION
        "init=epsg:3857"
    END
    CONFIG "PROJ_LIB" "C:/somedir/proj"
    ...
```

Error text:

```
msProcessProjection(): proj
error "No such file or directory" for "init=epsg:3857"
```
But this works fine:

```
MAP
    CONFIG "PROJ_LIB" "C:/somedir/proj"
    PROJECTION
        "init=epsg:3857"
    END
    ...
```
 Is it expected behavior that `CONFIG ` within `MAP` have to be placed before `PROJECTION`?

**Comment by sdlime** [comment]
Yes, this is expected. The code that processes the projection directive also initializes the projection object - hence the error message your see. Otherwise we'd need to initialize the projections at the end of the mapfile loading process which could have a number of side-effects. It hasn't been a big problem to date so I think it's better to leave "as is". -Steve

**Comment by drnextgis** [comment]
Such behavior is not obviously, so it would be useful include this in docs.

**Comment by sdlime** [comment]
Agreed - I'll create a documentation ticket.

**Comment by sdlime** [comment]
See https://github.com/mapserver/docs/issues/124... --Steve
