### ISSUE TITLE
Apache 2.4 Reload leads to crash of mod_auth_openidc module only when PHP mapscript is loaded

### ISSUE THREAD

**Issue by akrherz** [mapserver/mapserver#5263]
So an epic goose chase can be found on the pingidentity/mod_auth_openidc#122 ticket.  Basically, when I reload Apache 2.4 on RHEL7, subsequent requests that involve the mod_auth_openidc module all crash.  But this situation only happens when PHP Mapscript 7.0.1 is loaded at the same time!  A perhaps similiar report can be found [here](http://osdir.com/ml/mapserver-development/2015-02/msg00001.html).

I figured I'd open a ticket here as well and see if you folks had any ideas on how to persue resolving this situation. I was hoping to go the `dl()` load route to isolate out mapscript, but that appears to be difficult to do these days with even PHP in CGI mode.

**Comment by dmorissette** [comment]
We used to see behaviors like this several years ago when MapServer and PHP were compiled using different regex versions (resulting in different object sizes of the regex_t struct and causing seg faults).The solution was to ensure that all components were built using the exact same base libraries.

I don't think your problem has anything to do with regex, but MapServer (and PHP MapScript) do use libcurl and libssl which are also openidc dependencies, so I'd suggest making sure you are using the exact same version of those two in your PHP MapScript build.

Another suggestion to troubleshoot this, start with the most basic possible MapServer config and add components/dependencies one by one until you identify which dependency causes this. Note that GDAL is huge and carries local copies of several dependencies, so if the issue is not related to libcurl/libssl then the next piece I would look at disabling is gdal/ogr.

**Comment by akrherz** [comment]
@dmorissette Thank you so much for the very helpful response.  I recall now that regex fun.  The mod_auth_openidc crashes appear to be with its JSON (jansson) usage.  I will do as you suggest and see about trimming down mapscript until I find a working config.

**Comment by akrherz** [comment]
It appears I was able to isolate the issue to the inclusion of GDAL (1.11.4 from EPEL) in PHP Mapscript. Now the issue is that I think I need GDAL for my mapserver installation.  Uffties.

**Comment by akrherz** [comment]
Eh, I think I further isolated the issue down to Proj 4.9, I reverted back to 4.8 and all appears to be happy.  Oye.  Hopefully this goose chase helps somebody else out!

**Comment by dmorissette** [comment]
I find it odd that PROJ alone would explain this issue as it does not come with external dependencies shared with openidc AFAIK. Anyway, I'd suggest that you keep an eye on your server logs in case the bug shows up again in a different place.
