### ISSUE TITLE
issue CONNECTIONTYPE POSTGIS

### ISSUE THREAD

**Issue by ctl2016** [mapserver/mapserver#5363]
CONNECTIONTYPE POSTGIS
CONNECTION "host=localhost port=5432 dbname=test user=postgres password=123456" 
DATA "wkb_geometry from public.xzqy using unique ogc_fid using srid=4326"

In mapfile, when I use layer source data CONNECTIONTYPE POSTGIS to display map layer mapserv.exe, shp2img.exe and mapmanger.exe can't get the result, my computer's cpu will be 100%;

D:\Downloads\ms4w\apps\test>shp2img -m test.map -o test.png -l "xzqy" -all_debug

the log message show "msPostGISLayerWhichShapes query status: PGRES_TUPLES_OK (2)", the layer data already be queried.

D:\Downloads\ms4w>mapserv -v
MapServer version 7.0.1 (MS4W 3.1.4) OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=
PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=ICONV SUPPORTS=FRIBI
DI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIE
NT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=THREADS SUP
PORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE

WINDOWS 7 (64bits)

**Comment by jratike80** [comment]
This can't be a general bug in Mapserver. I run Mapserver from MS4W on my windows computer with similar PostGIS layers that you have without problems. I believe that your problem is real, still. Please write a mail to mapserver-users list and describe your environment. I am sure that we will find a solution for you. I am closing this ticket now, see you on the mailing list.

**Comment by ctl2016** [comment]
thanks your replay
I have solved this problem, the reason is:

file public.xzqy has chinese string and the file's encoding is not utf8
