### ISSUE TITLE
add metadata to optionally not emit root layer name in WMS Capabilities XML

### ISSUE THREAD

**Issue by tomkralidis** [MapServer/MapServer#5404]
A sample GetCapabilities request shows the following:

```xml
...
<Capability>
...
<Layer>
 <Name>foo</Name>
 <Title>bar</Title>
...
```

The root layer element's `foo` value is derived from the mapfile's `MAP.NAME` value.  WMS says any `Layer` with a `Name` element should be `GetMap` capable.  In our case this requests all layers in the WMS, which may prove problematic for a number of reasons:

1. potential performance issue
1. if one layer is broken/not functioning, will result in error
1. even on a successful request, the result is not meaningful/valuable

The workaround is to set `MAP.NAME` to `""`.  The proper fix is to tell MapServer to not emit the root layer name via something like `"wms_rootlayer_name_enabled" "false"`

**Comment by jratike80** [comment]
Hi,


> The proper fix is to tell MapServer to not emit the root layer name via something like wms_rootlayer_name_enabled


For my mind the default value should be to not emit the root layer name because in most cases users do not really want to do that. Same discussion was going on in the Geoserver issue tracker some time ago https://osgeo-org.atlassian.net/browse/GEOS-7935.


-Jukka Rahkonen-

**Comment by tomkralidis** [comment]
cc @dmorissette @rouault for thoughts.

@jratike80 I would tend to agree however I'm not sure how many installations utilize the functionality (imagine a 2 layer mapfile where is it easy to just call the root layer) already, so the concern is breaking existing applications.

**Comment by tomkralidis** [comment]
FYI PR in #5405 pending consensus.

**Comment by jratike80** [comment]
Copy of the the comment that I wrote to PR follows because I think this is where it belongs.

I think that also the WMS documentation http://mapserver.org/ogc/wms_server.html should be updated from this place:

> Map Name and wms_title:
> WMS Capabilities requires a Name and a Title tag for every layer. The Map’s NAME and wms_title metadata will be used to set the root layer’s name and title in the GetCapabilities XML output. The root layer in the WMS context corresponds to the whole mapfile.

Did you consider an alternative to add an explicit new metadata item "wms_name" that would override the name of the mapfile? The same effect than by setting
`"wms_rootlayer_name_enabled" "yes"`
would be obtained then by setting an empty wms_name
`"wms_name" ""`
That might be more user friendly because at the moment and with this change also in the future the WMS title is set in metadata but WMS name in a different and sort of non-logical place.

**Comment by dmorissette** [comment]
(Ooppss... copying my comment from the PR here)

I agree with @jratike80's comment and suggestion of setting "wms_name" "" instead of creating a new "wms_rootlayer_name_enabled" metadata.

**Comment by tomkralidis** [comment]
@jratike80 so implement `wms_name` instead (suggest calling this `wms_rootlayer_name`)?  Isn't implementing `"wms_name"` the same effect as setting `MAP.NAME` to `""`, then?

**Comment by tomkralidis** [comment]
@dmorissette ^^

**Comment by jratike80** [comment]
Yes, wms_rootlayer_name would be consistent with existing wms_rootlayer_abstract, wms_rootlayer_keywordlist, and wms_rootlayer_title.

I was thinking that "wms_name" would have the same effect than MAP NAME but just interpreted later and having precedence . But by looking at WMS standard that name is not good because it makes user to think that it would be a pair to "wms_title" which sets title for the whole service. However, the standard mandates that the service name is always "WMS". So forget "wms_name".

New "wms_rootlayer_name" would make is possible to have different names in MAP-NAME and MAP-METADATA-"wms_rootlayer_name".  You may consider if this is good or not. From the documentation I can't find especially much use for MAP-NAME

> NAME [name]
>     Prefix attached to map, scalebar and legend GIF filenames created using this mapfile. It should be kept short. 

Some edits to documentation would be needed: a new entry for wms_rootlayer_name and some edits to "Map Name and wms_title" and perhaps a new bullet item for the name of the root layer.

**Comment by tomkralidis** [comment]
@jratike80 PR #5405 updated.  Logic sequence in pseudo code:
```
if MAP.WEB.METADATA.wms_rootlayer_name is set and is not ""
    emit MAP.WEB.METADATA.wms_rootlayer_name
else
    proceed as normal/existing behaviour
```
Makes sense? We can merge and then update docs if this works for you.

**Comment by jratike80** [comment]
Thinking about `and is not ""`. It means that if MAP>NAME is set there is no way to prevent it from appearing as the name of the root_layer. 

```
if MAP.WEB.METADATA.wms_rootlayer_name is set and 
     if MAP.WEB.METADATA.wms_rootlayer_name is ""
           remove root layer name from GetCapabilities
     else
           emit MAP.WEB.METADATA.wms_rootlayer_name
else
    proceed as normal/existing behaviour
```

Would that make sense?

**Comment by tomkralidis** [comment]
@jratike80 even if MAP.NAME is set wms_rootlayer_name (if set) overrides it. See the tests as part of the PR. Note that existing tests pass as well so the PR does not break existing functionality. Or are you thinking to not emit the root layer name as a default?

**Comment by jratike80** [comment]
Emit root layer name is for sure useful. I was just thinking about a small corner case when user, for some reason, would like to override root layer name that heritages from MAP-NAME into nothing and remove the name element from GetCapabilities XML.

I was reading just your pseudocode 
if MAP.WEB.METADATA.wms_rootlayer_name is set and is not ""
which made me believe that if wms_rootlayer_name is set and IS an empty string "" then the rootlayer name from MAP-NAME is kept.

I am only a user who does not really write nor read code but test msautotest/wxs/ows_wms_rootlayer_name_empty.map  actually seems to test overriding MAP-NAME into empty.

In test msautotest/wxs/ows_wms_rootlayer_name.map you have perhaps done copy-paste without edit:
+# Results expected
+# getcapabilities: root <Layer> element does not emit <Name> element
Shouldn't it be the opposite and give Name "foo" as a result?

**Comment by tomkralidis** [comment]
>Emit root layer name is for sure useful. I was just thinking about a small corner case when user, for some >reason, would like to override root layer name that heritages from MAP-NAME into nothing and >remove the name element from GetCapabilities XML.
>
>I was reading just your pseudocode
>if MAP.WEB.METADATA.wms_rootlayer_name is set and is not ""
>which made me believe that if wms_rootlayer_name is set and IS an empty string "" then the rootlayer >name from MAP-NAME is kept.
>

If wms_rootlayer_name is "" then rootlayer name from MAP-NAME is not kept.  The test case in `/msautotest/wxs/ows_wms_rootlayer_name.map` should take care of this corner case.

>I am only a user who does not really write nor read code but test msautotest/wxs/ows_wms_rootlayer_name_empty.map actually seems to test overriding MAP-NAME into empty.
>
>In test msautotest/wxs/ows_wms_rootlayer_name.map you have perhaps done copy-paste without edit:
>+# Results expected
>+# getcapabilities: root element does not emit element
>Shouldn't it be the opposite and give Name "foo" as a result?

Typo in `msautotest/wxs/ows_wms_rootlayer_name.map` now fixed.

Thanks for the valuable comments and discussion!  Ok to merge PR?

**Comment by mkofahl** [comment]
Have you tried setting MAP.NAME to ""? As far i remember, this makes to root layer name disappearing.Kind regards, Martin.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Von: Tom KralidisGesendet: Samstag, 18. März 2017 00:50An: mapserver/mapserverAntwort an: mapserver/mapserverCc: SubscribedBetreff: Re: [mapserver/mapserver] add metadata to optionally not emit root layer name in WMS Capabilities XML (#5404)
Emit root layer name is for sure useful. I was just thinking about a small corner case when user, for some >reason, would like to override root layer name that heritages from MAP-NAME into nothing and >remove the name element from GetCapabilities XML.
I was reading just your pseudocode
if MAP.WEB.METADATA.wms_rootlayer_name is set and is not ""
which made me believe that if wms_rootlayer_name is set and IS an empty string "" then the rootlayer >name from MAP-NAME is kept.

If wms_rootlayer_name is "" then rootlayer name from MAP-NAME is not kept.  The test case in /msautotest/wxs/ows_wms_rootlayer_name.map should take care of this corner case.

I am only a user who does not really write nor read code but test msautotest/wxs/ows_wms_rootlayer_name_empty.map actually seems to test overriding MAP-NAME into empty.
In test msautotest/wxs/ows_wms_rootlayer_name.map you have perhaps done copy-paste without edit:
+# Results expected
+# getcapabilities: root element does not emit element
Shouldn't it be the opposite and give Name "foo" as a result?

Typo in msautotest/wxs/ows_wms_rootlayer_name.map now fixed.
Thanks for the valuable comments and discussion!  Ok to merge PR?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mapserver/mapserver","title":"mapserver/mapserver","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mapserver/mapserver"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tomkralidis in #5404: \u003eEmit root layer name is for sure useful. I was just thinking about a small corner case when user, for some \u003ereason, would like to override root layer name that heritages from MAP-NAME into nothing and \u003eremove the name element from GetCapabilities XML.\r\n\u003e\r\n\u003eI was reading just your pseudocode\r\n\u003eif MAP.WEB.METADATA.wms_rootlayer_name is set and is not \"\"\r\n\u003ewhich made me believe that if wms_rootlayer_name is set and IS an empty string \"\" then the rootlayer \u003ename from MAP-NAME is kept.\r\n\u003e\r\n\r\nIf wms_rootlayer_name is \"\" then rootlayer name from MAP-NAME is not kept.  The test case in `/msautotest/wxs/ows_wms_rootlayer_name.map` should take care of this corner case.\r\n\r\n\u003eI am only a user who does not really write nor read code but test msautotest/wxs/ows_wms_rootlayer_name_empty.map actually seems to test overriding MAP-NAME into empty.\r\n\u003e\r\n\u003eIn test msautotest/wxs/ows_wms_rootlayer_name.map you have perhaps done copy-paste without edit:\r\n\u003e+# Results expected\r\n\u003e+# getcapabilities: root element does not emit element\r\n\u003eShouldn't it be the opposite and give Name \"foo\" as a result?\r\n\r\nTypo in `msautotest/wxs/ows_wms_rootlayer_name.map` now fixed.\r\n\r\nThanks for the valuable comments and discussion!  Ok to merge PR?"}],"action":{"name":"View Issue","url":"https://github.com/mapserver/mapserver/issues/5404#issuecomment-287498212"}}}

**Comment by jratike80** [comment]
Ok to merge PR.

**Comment by tomkralidis** [comment]
@mkofahl correct, setting `MAP.NAME` does indeed suppress the root Layer name, however there are cases where we want `MAP.NAME` set (temp files creation, etc.)

**Comment by tomkralidis** [comment]
@jratike80 thanks, merging.

**Comment by tomkralidis** [comment]
FYI docs PR in https://github.com/mapserver/docs/pull/168

**Comment by jratike80** [comment]
I trust that the commit in year 2017 resolved this issue.
