### ISSUE TITLE
Mapscript cannot compile with a static libmapserver

### ISSUE THREAD

**Issue by alexbrault** [MapServer/MapServer#5425]
Whan attempting to compile Python Mapscript (I haven't tried any other flavour of Mapscript, but it stands to reason they'd encounter the same problem) with the static libmapserver, the linker throws an error about relocation: 
```
$ cmake .. -DLINK_STATIC_LIBMAPSERVER=1 -DWITH_PYTHON=1; make
[...]
/usr/bin/ld: ../../libmapserver_static.a(cgiutil.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
../../libmapserver_static.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
mapscript/python/CMakeFiles/_pythonmapscript.dir/build.make:143: recipe for target 'mapscript/python/_mapscript.so' failed
make[3]: *** [mapscript/python/_mapscript.so] Error 1
[...]
```

**Comment by juliensam** [comment]
The following thread is suggesting to add `-fPIC` to `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS`. MapScript does compile when doing so.

http://stackoverflow.com/questions/9637551/relocation-r-x86-64-32s-against-rodata-while-compiling-on-64-bit-platform

Since I don't understand the implication of the flag, I won't submit a pull request, but it could give someone else a good pointer to permanently solve the problem.

**Comment by alexbrault** [comment]
[This other StackOverflow question](http://stackoverflow.com/questions/38296756/what-is-the-idiomatic-way-in-cmake-to-add-the-fpic-compiler-option) suggests using the POSITION_INDEPENDENT_CODE CMake property as the canonical way to set the PIC flag in all compilers, and it did fix my compilation, but I'm not sure what the full implications are either
