### ISSUE TITLE
IN operator is not working with PostGIS expression translation

### ISSUE THREAD

**Issue by sdlime** [mapserver/mapserver#5490]
MapServer expressions with the IN operator are not being translated to native SQL for PostGIS. Should verify that other drivers aren't suffering from the same oversight. 

This primarily affects attribute queries where expressions must be given as MapServer expressions. Filters are also affected but there are a couple of workarounds in that case:

1. use the NATIVE_FILTER processing key
2. put the SQL directly in the DATA statement

--Steve

**Comment by ejn** [comment]
Just run into this problem too - `FILTER ('[attr]' IN 'my,list,of,items')` gets translated to `"attr"::text'my,list,of,items'`

@sdlime, have you made progress on this? Since it has now missed the 7.2 release, would it be worth putting a warning in the documentation until it gets fixed in a release?

**Comment by sdlime** [comment]
Am working on a fix now - in the 7.0 branch... Trick is handling both string and numeric lists.

**Comment by sdlime** [comment]
The fix has been added into the 7.2 branch, feel free to give it a try and let me know if you run into issues. I've added some regression tests and it seems to work fine. Closing... --Steve
