### ISSUE TITLE
Missing '$' when parsing ogc:PropertyIsLike ?

### ISSUE THREAD

**Issue by pmauduit** [mapserver/mapserver#5825]
When a regex is generated from a `ogc:propertyIsLike` filter, a '^' is prepended to the search, but we cannot find the line end ('$').

For example, with the following snippet in our SLD:

```xml
<ogc:PropertyIsLike escapeChar="\" matchCase="false" singleChar="?" wildCard="*">
  <ogc:PropertyName>PROGRAMMES</ogc:PropertyName>
  <ogc:Literal>REPHYTOX</ogc:Literal>
</ogc:PropertyIsLike>
```

The corresponding SQL statement is generated:

```sql
REGEXP_LIKE( PROGRAMMES, '^REPHYTOX','i' ) 
```

If a '^' is appended, why isn't there also a '$' added at the end of the pattern ?

One would have expected the following:

```sql
REGEXP_LIKE( PROGRAMMES, '^REPHYTOX$','i' ) 
```

The '^' seems to be added in this code:
https://github.com/mapserver/mapserver/blob/master/mapogcfiltercommon.c#L100-L103

This might be related to this previous work: https://github.com/mapserver/mapserver/pull/5739

**Comment by geographika** [comment]
@rouault - the commit at https://github.com/mapserver/mapserver/commit/eea166a5157d4742b617cd7561c62cd2df5c8f5c which adds the $ character causes an issue in the mssql driver (and possibly others database drivers?). 

The SQL clause generated by the filter is now:

`
WHERE ((LOWER([OwnerName]) LIKE LOWER('%Unknown%$')))
`

Which returns no results due to the $
