### ISSUE TITLE
SWIG - wrong result in rectObj->project()

### ISSUE THREAD

**Issue by richie21** [mapserver/mapserver#6004]
Hi. I noticed a difference between the result of the `$rectObj->project()` and the result of the `$pointObj->project()`.

```php
$szIn  = 'epsg:2154';
$szOut = 'epsg:3942';

$projectionIn  = new projectionObj($szIn);
$projectionOut = new projectionObj($szOut);

// via rectObj->project
echo '<h1>Test rectObj->project</h1>';
$rectObj = new rectObj(850918.52786522, 6690138.8970524, 857689.90623992, 6696422.7361841);
echo $szIn.' : '.$rectObj->minx.' '.$rectObj->miny.' '.$rectObj->maxx.' '.$rectObj->maxy.'<br>';
$rectObj->project($projectionIn, $projectionOut);
echo $szOut.' : '.$rectObj->minx.' '.$rectObj->miny.' '.$rectObj->maxx.' '.$rectObj->maxy.'<br>';

// via pointObj->project
echo '<h1>Test pointObj->project</h1>';
$oPoint1 = new pointObj();
$oPoint1->setXY(850918.52786522, 6690138.8970524);
$oPoint2 = new pointObj();
$oPoint2->setXY(857689.90623992, 6696422.7361841);
echo $szIn.' : '.$oPoint1->x.' '.$oPoint1->y.' '.$oPoint2->x.' '.$oPoint2->y.'<br>';
$oPoint1->project($projectionIn, $projectionOut);
$oPoint2->project($projectionIn, $projectionOut);
echo $szOut.' : '.$oPoint1->x.' '.$oPoint1->y.' '.$oPoint2->x.' '.$oPoint2->y;
```

It gives this output :
> **Test rectObj->project**
> epsg:2154 : 850918.52786522 6690138.8970524 857689.90623992 6696422.7361841
> epsg:3942 : 1851701.3569686 1790897.8989206 1858520.7245101 1797228.1741163
> 
> **Test pointObj->project**
> epsg:2154 : 850918.52786522 6690138.8970524 857689.90623992 6696422.7361841
> epsg:3942 : 1851701.3569686 1790911.5942995 1858520.7245101 1797214.4631788

The results should be consistent.

The result of the `$rectObj->project()` method seems to be incorrect.
While the result of `the $pointObj->project()` method is correct ([epsg.io](https://epsg.io/transform#s_srs=2154&t_srs=3942&x=857689.9062399&y=6696422.7361841))

Problem reproduced on MapServer 6.4.1, 7.4.1, 7.6-dev.
Problem reproduced with other projections (ex : 4326).

**Comment by rouault** [comment]
This is not a bug. This is intended. Rectangle reprojection does not only reproject the 4 corner points, but a number of points along each edges.

**Comment by richie21** [comment]
OK even if it's a little surprising (as a result).
Thank you for your quick reply.

**Comment by jratike80** [comment]
A late comment: That it is intented means that sometimes reprojecting just corner coordinates does not give a correct result.  For example if the source is in EPSG:4326 but the result is some system where latitude lines have a curvature, see for example https://tmackinnon.com/wp-content/uploads/utm_zone_map_canada-ft.jpg. If the envelope is first densified to have more points it is possible to make the result to follow the curvature. The envelope of the now curved polygon is different to the envelope of the polygon that is constructed from just the corner points. This is normal and correct.

However, I am not sure if such curvature appears in your conversion between EPSG:2145 and EPSG:3942 and if densification plays any role. I believe that the case is more simple: the conversion rotates the original bounding box and after that the min/max x and y are not where you suppose them to be. Actually the min y is at the lower right corner and max y is at the upper left corner of the slightly rotated polygon. You did not test those points at all with your  pointObj->project test, probably because rotation did not come into your mind and because the rotation is so small that it is not visible to bare eyes.

This is the rotated polygon and you can find both the "correct" and "wrong" y coordinates from it.

```
POLYGON ((
        1851701.3569685277 1790911.5943014827, 
        1851713.794611447 1797228.1741182571, 
        1858520.724510085 1797214.4631807813, 
        1858507.7291027775 1790897.8989225691, 
        1851701.3569685277 1790911.5943014827
    )) 
```
