### ISSUE TITLE
PHPMapScript vulnerabilities in error handling

### ISSUE THREAD

**Issue by jmckenna** [mapserver/mapserver#6014]
- Public ticket to record reported PHPMapScript vulnerabilities in error handling, initially reported by  @0xbigshaq 

- Patch has been created and will now be applied to branches 6.4, 7.0, 7.2, 7.4, master, and new releases of 6.4.6, 7.4.4 and 7.6.0

- **Note** that these vulnerabilities do not affect SWIG MapScript support, and this ticket should be a strong hint to all users and packagers to switch to the maintained SWIG MapScript PHP7 support.

**Comment by jmckenna** [comment]
Fixed in 7.4.4 and 6.4.6 releases.

**Comment by sdlime** [comment]
This issue addresses:

**CVE-2020-10872**: A buffer overflow in PHP/MapScript exception handling in MapServer through 7.4 could result in denial of service or remote code execution.

**CVE-2020-10873**: PHP/MapScript exception handling in MapServer through 7.4 could result in leaking values from the stack because of a double vsprintf call.
