### ISSUE TITLE
Failure in AppVeyor builds

### ISSUE THREAD

**Issue by rouault** [mapserver/mapserver#6054]
Starting with today commits, AppVeyor builds mysteriously fail with 
```
============================= test session starts =============================
  platform win32 -- Python 2.7.17, pytest-4.6.9, py-1.8.1, pluggy-0.13.1
  rootdir: C:\projects\mapserver\build\mapscript\python\Release
  collected 0 items
  
  ======================== no tests ran in 0.03 seconds =========================
CUSTOMBUILD : error : file or package not found: mapscript.tests (missing __init__.py?) [C:\projects\mapserver\build\mapscript\python\pythonmapscript-wheel.vcxproj]
```

Last known working build: https://ci.appveyor.com/project/MapServer/mapserver/builds/32201946/job/rigrxagjllsnvqiv
First non-working build: https://ci.appveyor.com/project/MapServer/mapserver/builds/32253726/job/k7nvcnpmq5a9b42i

**Comment by rouault** [comment]
@geographika Any idea ?

**Comment by geographika** [comment]
@rouault - looking at it now. The versions / logs are identical up to the point of failure.
Looks like it might be a py2-only issue.

**Comment by geographika** [comment]
@rouault @szekerest - the issue is that the GDAL DLLs are no longer present in the SDKs used by Appveyor. See https://www.gisinternals.com/query.html?content=filelist&file=release-1911-dev.zip and https://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-dev.zip

@szekerest - is this by design (the SDKs should now be used to compile GDAL from scratch) or a temporary issue?

It is unrelated to Python/MapScript - the mapserv.exe doesn't run either.

**Comment by rouault** [comment]
I presume this is a unwanted failure. Tamas did a change yesterday in the build configuration, so the build must have somehow failed.

**Comment by geographika** [comment]
This is up and running again, and hopefully running the mapserv.exe to show the [version output](https://ci.appveyor.com/project/MapServer/mapserver/builds/32399594/job/fm5etrmcesqmb1n0#L454) will make the issue clearer if this happens again.
