### ISSUE TITLE
Mapscript circular import error

### ISSUE THREAD

**Issue by akudekar** [MapServer/MapServer#6228]
A simple Python-Flask Mapscript inside Docker with and without Python Venv creates a circular import error on Docker run.

``` 
import mapscript
from flask import Flask
import json

app = Flask(__name__)
port = 5000

@app.route("/hello")
def geocoder():


    epsg = mapscript.pointObj(1, 1)
    return json.dumps(epsg)

    test()

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=port)
```
Dockerfile

```
FROM python

WORKDIR /opt/demo/
COPY /app .

RUN pip install -r requirements.txt

ENTRYPOINT python test.py
```

Error
```
Traceback (most recent call last):
  File "/opt/demo/test.py", line 1, in <module>
    import mapscript
  File "/usr/local/lib/python3.9/site-packages/mapscript/__init__.py", line 2, in <module>
    from .mapscript import *
  File "/usr/local/lib/python3.9/site-packages/mapscript/mapscript.py", line 13, in <module>
    from . import _mapscript
ImportError: cannot import name '_mapscript' from partially initialized module 'mapscript' (most likely due to a circular import) (/usr/local/lib/python3.9/site-packages/mapscript/__init__.py)
```

**Comment by akudekar** [comment]
Error

**Comment by jmckenna** [comment]
Thanks for first asking this on the mailing list first, let's see if other users help there.  Closing.

**Comment by mradamcox** [comment]
I'm getting a circular import error when using a venv install. I see there has been [a response](https://lists.osgeo.org/pipermail/mapserver-users/2021-February/082019.html) but no further troubleshooting there. Any progress here?

This is what happens for me on Ubuntu 20.04, python 3.8.5.
![2021-06-07_mapserver-install-problem](https://user-images.githubusercontent.com/10427268/121040043-36d69400-c777-11eb-9dcb-5d6f7176b8bb.png)

Then I double-checked to make sure the system packages were installed as mentioned in the mailing list.
![2021-06-07_mapserver-install-problem-2](https://user-images.githubusercontent.com/10427268/121040046-3807c100-c777-11eb-9678-27fcc3ff48c4.png)

**Comment by akudekar** [comment]
Hi Adam,

Try running mapscript outside the venv. That worked for me.

Warm regards,

Aditya Kudekar
Institute for Geoinformatics
University of Münster
***@***.***

**Comment by mradamcox** [comment]
Ok, I just did try pip installing it into my global python 3, but the exact same thing happened. Ultimately, I do need it to run from within a virtual env. I can make a new ticket if that would be better.

**Comment by akudekar** [comment]
Can you try to install python3-mapscript using apt-get instead of pip and then use it? That worked for me to solve my docker issue

Warm regards,

Aditya Kudekar
Institute for Geoinformatics
University of Münster
***@***.***

**Comment by geographika** [comment]
Wheels have only been created for Windows builds, not Linux. When running `pip install mapscript` and a wheel for the relevant OS is not found then the source build (without the _mapscript.so file) will be installed, but this is only really useful for generating docs. This is the reason for the error message. 

You have 2 options:

1. Install mapscript globally using `sudo apt-get install python3-mapscript`. Then when creating new virtual environments use the `--system-site-packages` to allow the global packages to be used. 
2. Build MapServer on the OS you wish to deploy, and then create your own Linux Python mapscript wheel - see "Building the Mapscript Module" at https://pypi.org/project/mapscript/. You can then install the wheel to a virtual environment by pointing pip to the folder containing the wheel (rather than using pypi) - `pip install --no-index --find-links=folder_name mapscript`

I looked briefly at making Linux wheels to upload to pypi, but as I understand it you have to use a very old base version of Linux that it was not possible to build MapServer on. This may have since changed, see https://github.com/pypa/manylinux

**Comment by mradamcox** [comment]
Ok, thank you both for your help. @geographika I appreciate the extra context, and using `--system-site-packages` did allow me to install `mapscript` into a new virtual env. Solved!

I guess when I tried pip installing it into my global python earlier I must have done something wrong, because I've tried that again as well and it does work properly (which follows, of course).
