### ISSUE TITLE
DATARANGE and COLORRANGE doesn;t work with GeoTiff with band datatype byte

### ISSUE THREAD

**Issue by igieon** [MapServer/MapServer#6287]
## Expected behavior and actual behavior.
I use in mapfile:
```
CLASS
	EXPRESSION ([pixel] !=38)
	STYLE
	COLOR 00 00 00 
	END
	
END	
CLASS
	EXPRESSION ([pixel] == 38)
	STYLE
		COLORRANGE 0 0 0 100 0 0
		DATARANGE 0 100
	END
END
```
Rendered pixel has value in image is 100 0 0 not as expected 38 0 0. Input geotif has band datatype byte. When i convert geotiff to int16 or uint everything works as expected.
I include zip file contains ok and wrong map file points to different geotiff 
[report.zip](https://github.com/MapServer/MapServer/files/6280241/report.zip)

**Comment by rouault** [comment]
The issue is more with your data. water_status-2021-04-07_5.tif, of type Byte, uses a color table.
With gdalinfo on it, one can see that entry 38 of that color table is:
   38: 188,0,0,255

The color interpolation done in that mode uses the red value of the color table entry, here 188, to do the interpolation.
With current versions, this will result in a 188,0,0 output value, due to a lack of validation against the DATARANGE. Fix to be submitted to add extra validation

**Comment by igieon** [comment]
Yes i know that i have there color table, but i want to override it. Nevermind i use plain value now without color table as i write using float datatype and then everything is worked as expected.
