### ISSUE TITLE
LABEL->PARTIALS default unclear

### ISSUE THREAD

**Issue by mrclBIE** [MapServer/MapServer#6334]
According to the [Migration Guide](https://mapserver.org/MIGRATION_GUIDE.html#mapserver-7-0-to-7-2-migration) **LABEL->PARTIALS now defaults to “FALSE” instead of “TRUE”**. But in the [documentation](https://www.mapserver.org/mapfile/label.html?highlight=partials) it is called, that the default is true. What is correct?

**Comment by jratike80** [comment]
We have mapserver-users mailing list that we recommend to use for asking questions, because just knowing your problem may be important for other users, and even more if you happen to get an useful answer. If it appears that you have found an error in the documentation then you can make the bug report later.

Do you have service up for making a test? Open the layer without PARTIAL keyword with WMS client and pan the map.  See if the labels near the border are either totally visible or totally off or if you can see partials. If you don't see partials then the  documentation is outdated.

I am not sure what file to fix if there is an error. The same description appears also here https://github.com/MapServer/MapServer/blob/2c3767a5bf8cfec610c59758206ae267c2ada622/mapserver.h.

**Comment by mrclBIE** [comment]
Ok, sorry. I thought at first, that i can fix the bug in the documentation but didn´t found the docs here. I tested it with MapServer 6.4.1 and 7.6.1. MapServer 6.4.1 defaults to PARTIALS true and MapServer 7.6.1 defaults to PARTIALS false. So the Migration Guide ist correct and the LABEL documentation needs to be updated.

**Comment by jratike80** [comment]
Try this workflow https://mapserver.org/development/documentation.html#workflow-for-simple-edits but keep the issue open because it seems to be that the comment in mapserver.h should be fixed as well.

**Comment by jmckenna** [comment]
@mrclBIE if you find a bug in the documentation please always file the ticket in the documentation repository: https://github.com/MapServer/MapServer-documentation/  I will update the docs now for this change.

**Comment by jmckenna** [comment]
For reference, the source code change was initially made through https://github.com/MapServer/MapServer/issues/5198

**Comment by jmckenna** [comment]
I think we can close this ticket now.  Any objections?  Thanks again for the find @mrclBIE  Please be sure to file any future documentation bugs in the documentation repository.

**Comment by jratike80** [comment]
Should we correct https://github.com/MapServer/MapServer/blob/2c3767a5bf8cfec610c59758206ae267c2ada622/mapserver.h#L1175 by the same?

**Comment by jmckenna** [comment]
> 
> 
> Should we correct
> 
ah sorry, I see your point, great catch @jratike80 The comment in the source is incorrect.  Lets correct that yes, willdo now...

**Comment by jmckenna** [comment]
I think it can now be closed.  Thanks again @mrclBIE & @jratike80 for the great catch.
