### ISSUE TITLE
Invalid namespace declarations in WFS DescribeFeatureType responses

### ISSUE THREAD

**Issue by geographika** [MapServer/MapServer#6924]
Currently all versions of WFS return the following namespaces for `DescribeFeatureType` requests:

```xml
<schema
   targetNamespace="http://mapserver.gis.umn.edu/mapserver" 
   xmlns:ms="http://mapserver.gis.umn.edu/mapserver" 
   xmlns:ogc="http://www.opengis.net/ogc"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns="http://www.w3.org/2001/XMLSchema"
   xmlns:gml="http://www.opengis.net/gml"
   elementFormDefault="qualified" version="0.1" >
```

Taken from [msautotest](https://github.com/MapServer/MapServer/blob/370afa1ff1ddd463a8569f6cd3f526bfc88a0ebc/msautotest/wxs/expected/wfs_200_describefeaturetype_outputformat_gml212.xml#L4)

`http://www.w3.org/2001/XMLSchema` is repeated twice - which seems to lead to ambiguities. It causes an issue in downstream libraries e.g. https://github.com/geopython/OWSLib/pull/887

Is the above correct? Or should ` xmlns="http://www.w3.org/2001/XMLSchema` be removed?

**Comment by rouault** [comment]
My understanding is that this is perfectly valid. See the examples from OGC : https://schemas.opengis.net/wfs/2.0/examples/DescribeFeatureType/DescribeFeatureType_Example01_Response.xsd

```
<schema 
   targetNamespace="http://www.someserver.example.com/myns"
   xmlns:myns="http://www.someserver.example.com/myns"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns="http://www.w3.org/2001/XMLSchema"
   xmlns:gml="http://www.opengis.net/gml/3.2"
   elementFormDefault="qualified" version="2.0.2">
```

AFAICS, in the usage made by MapServer, the xmlns:xsd could theoretically be removed (but that wouldn't solve the OWSLib bug as it seems the issue is the default xmlns namespace) as the XMLSchema elements are used without a ``xsd:`` prefix : ``import``, ``element``, etc. That is the ``xmlns="http://www.w3.org/2001/XMLSchema"`` attribute is required unless all elements and type values would be prefixed with ``xsd:``

**Comment by geographika** [comment]
Thanks @rouault - that makes sense - a default can be set as well as matching a prefix. Closing, and fix opened as a pull request to OWSLib. 

The confusing part of the spec was that XML attributes in the same element can't have _different_ prefixes that map to the same namespace (as per https://www.w3.org/TR/REC-xml-names/#uniqAttrs). They can have a non-prefix (default) and a prefix that map to the same namespace.
