### ISSUE TITLE
Add config file-level error redirection capability. 

### ISSUE THREAD

**Issue by sdlime** [MapServer/MapServer#6968]
Currently one can set the ERROR attribute in an individual mapfile. In the case of an error, the request is re-directed to URL. This is helpful for obfuscating errors and providing end-users with more meaningful instructions about what happened or what to do next. 

That said, it needs to be enabled on all mapfiles individually and doesn't catch all errors - most notably when an incorrect mapfile or mapfile alias is referenced. So, being able to set a similar value at the config file-level would be beneficial across multiple applications and would allow an administrator to control behavior on a global level.

Ideally an ERROR value set at the local level would take priority over the global value.

--Steve

**Comment by jratike80** [comment]
> Currently one can set the ERROR attribute in an individual mapfile.

I have never before met this error redirection. Is it documented somewhere, and are there usage examples?

**Comment by sdlime** [comment]
See https://mapserver.org/mapfile/web.html

**Comment by jratike80** [comment]
Oh, I have only used WMS/WFS/WCS and I think that during these 18 years I have never had anything else than METADATA in WEB. Never too late to learn more.

With a WMS mapfile it seems to be possible to show something else instead of 
"mapserv(): Web application error. Traditional BROWSE mode requires a TEMPLATE in the WEB section, but none was provided" when the request is not even an erroneous WMS request. I feel relieved, our users have not lost much because of my ignorance.

**Comment by sdlime** [comment]
Correct.  Any errors associated with mapfile loading can't be redirected though unless there's something configured some other way and this would do it. Note that you can also disable all other native modes using something like this in the WEB metadata.

```
    METADATA
      ...
      ms_enable_modes "!*" # OGC services only
    END
```
