### ISSUE TITLE
The support for GDAL drivers is not comprehensive enough, and there is a significant lack of drivers, such as for Parquet.

### ISSUE THREAD

**Issue by tpolong** [MapServer/MapServer#7149]
The support for GDAL drivers is not comprehensive enough, and there is a significant lack of drivers, such as for Parquet.

**Comment by jratike80** [comment]
I believe that if Mapserver is build with GDAL that supports Parquet or the other drivers that you lack, then Mapserver can use all those drivers. Please explain how did you install Mapserver.

**Comment by tpolong** [comment]
https://download.gisinternals.com/sdk/downloads/release-1930-x64-gdal-3-9-1-mapserver-8-2-0.zip,I use this

**Comment by jratike80** [comment]
The gisinternals site is an independent project that makes GDAL and MapServer packages. The Mapserver project does not decide what drivers are compiled into the GDAL version that gisinternals deliver.

Gisinternals document what drivers it supports, for example https://www.gisinternals.com/packageinfo.php?file=release-1930-x64-gdal-mapserver.zip. The site has also an own issue tracker https://www.gisinternals.com/issues.html. You can also contact Tamas Szekerest https://www.gisinternals.com/contact.html directly and negotiate a contract about making a special build for you.

It is also possible to build GDAL and Mapserver from the source code but it is probably somewhat complicated on Windows. That route is documented in https://mapserver.org/installation/index.html.

Anyway, I will close this ticket because the Mapserver project does not make the gisinternals builds, and generally speaking, Mapserver does not limit in any way what GDAL drivers are available.

**Comment by tpolong** [comment]
thank you
